import { Router } from 'express';
import { requireAccess, requireAdmin } from '../middleware/auth.js';
import { repository } from '../repositories/trustvault.repository.js';
import { requestedDelay, wait } from '../utils/delay.js';
import { hashPassword } from '../utils/security.js';

export const userRouter=Router();userRouter.use(requireAccess);
userRouter.get('/users',requireAdmin,async(req,res)=>{await wait(requestedDelay(req,1000));const s=await repository.get();res.json(s.users.map(repository.userView));});
userRouter.get('/users/check/:id',requireAdmin,async(req,res)=>{await wait(requestedDelay(req,300));const u=await repository.findUser(req.params.id);res.json({exists:!!u});});
userRouter.post('/users',requireAdmin,async(req,res)=>{await wait(requestedDelay(req,700));const {id,name,role,accessLevel}=req.body||{};if(!/^[a-z0-9_]{3,20}$/i.test(String(id||''))||!String(name||'').trim()){res.status(400).json({message:'Valid ID and name are required.'});return;}if(await repository.findUser(String(id))){res.status(409).json({message:'User ID already exists.'});return;}const s=await repository.get();const u={id:String(id).toLowerCase(),name:String(name).trim(),role:role==='Admin'?'Admin':'General User',accessLevel:String(accessLevel||'Beta (Internal)'),status:'Active',passwordHash:hashPassword(String(id).toLowerCase())};s.users.push(u);await repository.save(s);res.status(201).json(repository.userView(u));});
userRouter.put('/users/:id',requireAdmin,async(req,res)=>{await wait(requestedDelay(req,700));const s=await repository.get();const u=s.users.find(x=>String(x.id).toLowerCase()===req.params.id.toLowerCase());if(!u){res.status(404).json({message:'User not found'});return;}if(req.body?.name)u.name=String(req.body.name).trim();if(req.body?.role)u.role=req.body.role==='Admin'?'Admin':'General User';if(req.body?.accessLevel)u.accessLevel=String(req.body.accessLevel);await repository.save(s);res.json(repository.userView(u));});
userRouter.put('/users/:id/status',requireAdmin,async(req,res)=>{await wait(requestedDelay(req,800));const s=await repository.get();const u=s.users.find(x=>String(x.id).toLowerCase()===req.params.id.toLowerCase());if(!u){res.status(404).json({message:'User not found'});return;}if(u.id==='admin'){res.status(400).json({message:'Primary admin cannot be suspended.'});return;}u.status=u.status==='Active'?'Suspended':'Active';await repository.save(s);res.json(s.users.map(repository.userView));});
userRouter.delete('/users/:id',requireAdmin,async(req,res)=>{await wait(requestedDelay(req,700));const s=await repository.get();if(req.params.id==='admin'){res.status(400).json({message:'Primary admin cannot be deleted.'});return;}const before=s.users.length;s.users=s.users.filter(x=>x.id!==req.params.id);if(s.users.length===before){res.status(404).json({message:'User not found'});return;}await repository.save(s);res.json({ok:true});});
