import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { config } from './config.js';
import { repository } from './repositories/trustvault.repository.js';
import { authRouter } from './routes/auth.routes.js';
import { dataRouter } from './routes/data.routes.js';
import { userRouter } from './routes/user.routes.js';
import { auditRouter } from './routes/audit.routes.js';

const app=express();
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(cors({origin:config.corsOrigin==='*'?true:config.corsOrigin}));
app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
app.use(express.json({limit:'1mb'}));
app.use(morgan('tiny'));
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'trustvault-api',time:new Date().toISOString()}));
app.use('/api/auth',authRouter);
app.use('/api',dataRouter);
app.use('/api',userRouter);
app.use('/api',auditRouter);
app.use((err:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error(err);res.status(500).json({message:'Internal server error'});});
await repository.init();
app.listen(config.port,()=>console.log(`TrustVault Core API running on http://localhost:${config.port}`));
